$(document).ready(function(){
    $("#a_home").tooltip("show");
    $("#a_home").tooltip("hide");
    //
    $("#a_new_ass").tooltip("show");
    $("#a_new_ass").tooltip("hide");
    //
    $("#a_pay").tooltip("show");
    $("#a_pay").tooltip("hide");
    //
    $('#enrollmntId').tooltip("show");
    $('#enrollmntId').tooltip("hide");
    //
    $('#transactionNo').tooltip("show");
    $('#transactionNo').tooltip("hide");
    //
    $('#recentBal').tooltip("show");
    $('#recentBal').tooltip("hide");

});