$(document).ready(function(){
    /*CREATE ASSESSMENT*/
    $("#a_home").tooltip("show");
    $("#a_home").tooltip("hide");
    //
    $("#a_new_ass").tooltip("show");
    $("#a_new_ass").tooltip("hide");
    //
    $("#a_pay").tooltip("show");
    $("#a_pay").tooltip("hide");
    //
    $('#my_profile').tooltip("show");
    $('#my_profile').tooltip("hide");
    //
    $('#logout').tooltip("show");
    $('#logout').tooltip("hide");
    //
    $('#enrollmntId').tooltip("show");
    $('#enrollmntId').tooltip("hide");
    //
    $('#transactionNo').tooltip("show");
    $('#transactionNo').tooltip("hide");
    //
    $('#recentBal').tooltip("show");
    $('#recentBal').tooltip("hide");

    /*PAYMENT*/
    $('#p-span-date').tooltip("show");
    $('#p-span-date').tooltip("hide");
});